name: BlockLocker
main: com.zhufu.opencraft.BlockLocker
author: zhufucomcom
version: '1.0'
softdepend: [ServerCore]
api-version: '1.14'
commands:
  bl:
    usage: /bl
    description: 锁定一个方块，并给予其唯一标识符
  bl set:
    usage: /bl set <玩家> <方块块ID|组ID>
    description: 给予一个玩家访问某个区块的权限
  bl unset:
    usage: /bl unset <玩家> <方块ID|组ID|clear>
    description: 清除一个玩家访问某个区块或所有区块的权限
  bl del:
    usage: /bl del <方块ID|组ID>
    description: 删除指定ID的区块限制
  bl check:
    usage: /bl check <方块ID|组ID>
    description: 查看您所有的区块的玩家访问记录
  bl ->:
    usage: /bl <方块1> <方块2> <...> -> <组ID>
    description: 对指定区块进行归组
  bl <-:
    usage: /bl <方块1> <方块2> <...> <- <组ID>
    description: 取消指定区块的分组
  bl rename:
    usage: /bl rename [方块ID] <新ID>
    description: 为某一区块命名