name: CurrencySystem
author: zhufucomcom
main: com.zhufu.opencraft.CurrencySystem
version: '1.0'
depend:
  - ServerCore
api-version: '1.19'
commands:
  trade:
    usage: /trade (已被抛弃)
    description: 加入线上交易
  trade center:
    usage: /trade center
    description: 传送到交易世界枢纽
  trade back:
    usage: /trade back
    description: 回到您的交易世界领地
  trade give:
    usage: /trade give <玩家> <货币数>
    description: 给予某玩家指定数量的货币
  trade set:
    usage: /trade set <玩家> <货币数>
    description: 设置玩家的货币总数
  trade donation:
    usage: /trade donation
    description: 服务器捐赠通道，用于向玩家展示带有捐赠二维码的地图
  bank:
    usage: /bank
    description: 查询银行位置
  bank add:
    usage: /bank add [名称]
    description: 在此处放置银行服务员或指定名称的银行
    permission: op
  bank remove:
    usage: /bank remove [银行名称]
    description: 移除最近的银行服务员或指定的银行
    permission: op