name: PrevHacking
author: zhufucomcom
main: com.zhufu.opencraft.PrevHacking
version: 1.0
api-version: 1.13
commands:
  ph:
    usage: /ph set <...>
    description: PreHacking核心指令 (管理员操作)
  ph threhold:
    usage: /ph set <threshold|showPlayerOrePointingInfo> [自然数]
    description: 查看或设置踢出玩家的阈值