name: PlayerUtil
author: zhufucomcom
main: com.zhufu.opencraft.PlayerUtil
version: '1.0'
softdepend: [ServerCore]
api-version: '1.13'
commands:
  lu:
    usage: /lu <DTWB|RP|TP>
    description: 主城工具，用于生成迷你游戏
    permission: op
  pu:
    usage: /pu
    description: 玩家工具，显示一个交互界面
  lobby:
    usage: /lobby <玩家ID> [go|permit|forbid]
    description: 查看或拜访某人的主城，授权或禁止某人某人在主城协同建筑。