name: TenMinSur
main: com.zhufu.opencraft.TenMinSur
version: 1.0
author: zhufucomcom
depend:
  - ServerCore
api-version: 1.13
commands:
  tms:
    usage: /tms join
    description: 十分钟生存挑战
  tms join:
    usage: /tms join
    description: 加入游戏