name: Skinny
main: tw.davy.minecraft.skinny.Skinny
load: STARTUP
version: 1.1-SNAPSHOT
authors: [Davy, zhufucdev]
api-version: 1.19
depend:
  - ServerCore
commands:
  sc:
    usage: /<command> <目标玩家名称>
    description: 修改自己的皮肤，使之变为指定玩家的(只支持Mojang API)